# Generated by Django 3.1.3 on 2021-01-13 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetail',
            old_name='pincode',
            new_name='pin_code',
        ),
    ]
