# Generated by Django 3.1.3 on 2020-11-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_productdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetail',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
