# Generated by Django 3.1.3 on 2020-11-07 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201106_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='product_category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='password',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='pincode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userdetail',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
